### ISSUE TITLE
Process icon save/load doesn't work

### ISSUE THREAD

**Issue by DeepSkyForge** [DeepSkyForge/GraXpert4PixInsight#8]
If you create a prcess icon GraXpert and save it, you will get error message when you will try to load it later.
![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/157253452/0e79843f-3069-44b2-8617-f03b82979ae9)

Problem reported by astrobomb1 on Discord Dark Matter and confirmed.
I need to provide a fix.

Similar problem if you save a PixInsight project containing GraXpert process icon.
Scenario reported by Gert on Discord Dark Matter.

**Comment by ggalb** [comment]
Thank you Sir. I figured it out after seeing some comments on Dark Matters Discord. You probability realized that I was positing there too. 
The up to 2 minutes lacking was not related to running denoise but PI not responding because of the errors coming from the processing icon. I deleted it and all works fine now. Thank you for your help. Cheers

**Comment by DeepSkyForge** [comment]
I think, I'll release the fix no later than saturday.
It's already fixed but I need time to build package and pass all non regression tests on all platforms...

**Comment by DeepSkyForge** [comment]
Please upgrade to GraXpert Process version 2.0.2 to get the correction.
